version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=taskdb
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 